
language: java

jdk:
 - oraclejdk8

branches:
  only:
    - master

script: "./gradlew --no-daemon check test --info --continue --stacktrace"

after_success:
  - ./gradlew --no-daemon jacocoTestReport coveralls --info

